global:
  namespace: byc-cloud-platform
  imageRegistry: ""
  imagePullPolicy: IfNotPresent
  springProfile: prod

nacos:
  server: nacos.byc-cloud-platform.svc.cluster.local:8848
  namespace: ""
  group: DEFAULT_GROUP

services:
  gateway-service:
    enabled: true
    image: byc-cloud-platform/gateway-service
    tag: latest
    replicas: 1
    port: 8080
  user-service:
    enabled: true
    image: byc-cloud-platform/user-service
    tag: latest
    replicas: 1
    port: 8080
  sync-job:
    enabled: true
    image: byc-cloud-platform/sync-job
    tag: latest
    replicas: 1
    port: 8090
  rag-service:
    enabled: true
    image: byc-cloud-platform/rag-service
    tag: latest
    replicas: 1
    port: 8100
