seata:
    metrics:
        enabled: false
        exporter-list: prometheus
        exporter-prometheus-port: 9898
        registry-type: compact
    server:
        enable-check-auth: true
        enable-parallel-request-handle: true
        enableParallelRequestHandle: true
        max-commit-retry-timeout: -1
        max-rollback-retry-timeout: -1
        recovery:
            async-committing-retry-period: 1000
            committing-retry-period: 1000
            rollbacking-retry-period: 1000
            timeout-retry-period: 1000
        retry-dead-threshold: 130000
        rollback-failed-unlock-enable: false
        service-port: 8091
        session:
            branch-async-queue-size: 5000
            enable-branch-async-remove: false
        undo:
            log-delete-period: 86400000
            log-save-days: 7
        xaer-nota-retry-timeout: 60000
    store:
        db:
            branch-table: branch_table
            datasource: druid
            db-type: postgresql
            distributed-lock-table: distributed_lock
            driver-class-name: org.postgresql.Driver
            global-table: global_table
            lock-table: lock_table
            max-conn: 100
            max-wait: 5000
            min-conn: 10
            password: root
            query-limit: 1000
            url: jdbc:postgresql://postgresql:5432/seata
            user: root
        lock:
            mode: db
        mode: db
        session:
            mode: db
    transport:
        enable-tc-server-batch-send-response: false
        rpc-tc-request-timeout: 15000
        shutdown:
            wait: 3
        thread-factory:
            boss-thread-prefix: NettyBoss
            boss-thread-size: 1
            worker-thread-prefix: NettyServerNIOWorker
store:
    db:
        branch-table: branch_table
        datasource: druid
        db-type: postgresql
        distributed-lock-table: distributed_lock
        driver-class-name: org.postgresql.Driver
        global-table: global_table
        lock-table: lock_table
        max-conn: 100
        max-wait: 5000
        min-conn: 10
        password: root
        query-limit: 1000
        url: jdbc:postgresql://postgresql:5432/seata
        user: root
    lock:
        mode: db
    mode: db
    session:
        mode: db
