server.maxCommitRetryTimeout=-1
server.maxRollbackRetryTimeout=-1
server.recovery.asynCommittingRetryPeriod=1000
server.recovery.committingRetryPeriod=1000
server.recovery.rollbackingRetryPeriod=1000
server.recovery.timeoutRetryPeriod=1000
server.undo.logDeletePeriod=86400000
server.undo.logSaveDays=7
store.db.branchTable=branch_table
store.db.datasource=druid
store.db.dbType=postgresql
store.db.driverClassName=org.postgresql.Driver
store.db.globalTable=global_table
store.db.lockTable=lock_table
store.db.maxConn=20
store.db.maxWait=5000
store.db.minConn=1
store.db.password=root
store.db.queryLimit=100
store.db.url=jdbc:postgresql://postgresql:5432/seata
store.db.user=root
store.mode=db
