server:
  port: 8090

spring:
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 5s

app:
  job:
    sync:
      cron: "0 0/5 * * * ?"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus,scheduledtasks"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

logging:
  level:
    root: INFO
    com.byc: DEBUG
